name: example-test

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GOPRIVATE: "github.com/abema/crema"

jobs:
  example-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.25", "1.26"]
    services:
      valkey:
        image: valkey/valkey:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.3.1
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: v1-${{ runner.os }}-go-example-${{ matrix.go-version }}-${{ hashFiles('go.work.sum', '**/go.sum') }}
          restore-keys: |
            v1-${{ runner.os }}-go-example-${{ matrix.go-version }}-
      - name: setup-git
        run: git config --global url."https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/abema/crema".insteadOf "https://github.com/abema/crema"
      - name: Go test (example)
        run: go test ./example

  example-test-aggregate:
    name: example-test-aggregate
    runs-on: ubuntu-latest
    needs: example-test
    if: always()
    steps:
      - name: Check matrix result
        run: test "${{ needs.example-test.result }}" = "success"
