name: go-bench

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  GOPRIVATE: "github.com/abema/crema"

jobs:
  go-bench:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.25", "1.26"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.3.1
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: v1-${{ runner.os }}-go-bench-${{ matrix.go-version }}-${{ hashFiles('go.work.sum', '**/go.sum') }}
          restore-keys: |
            v1-${{ runner.os }}-go-bench-${{ matrix.go-version }}-
      - name: setup-git
        run: git config --global url."https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/abema/crema".insteadOf "https://github.com/abema/crema"
      - name: Go bench
        run: go test -v -run='^$' -bench=. -benchtime=1s ./... $(find ./ext/ -type d -mindepth 1 -maxdepth 1 | sed 's|$|/...|' | paste -sd ' ' -)
